World-Meteorological-Organization/csv2bufr

.gitignore, csv2bufr/__init__.py, csv2bufr/cli.py, tests/test_csv2bufr.py
=> move GeoJSON creation to module for reuse

csv2bufr/__init__.py, csv2bufr/resources/mappings/malawi_synop_bufr.json, csv2bufr/resources/mappings/mapping_schema.json, process_station.sh, tests/test_csv2bufr.py
Fixes bug where MT version number was ignored in the encoding.
=> Bug fix to include MT version number

Dockerfile
This PR optimizes the Docker image build by reducing the number of layers as well as the output image size by 2/3.
=> optimize Docker image build

csv2bufr/__init__.py, csv2bufr/cli.py, tests/test_csv2bufr.py
This PR changes `csv2bufr:transform` to return a generator for memory efficiency.
cc @webb-ben
=> change main transformation to generator

.github/workflows/ghcr.yml
=> add GitHub Container Registry action

README.md, csv2bufr/resources/mappings/wmo_om_rc0.geojson, docs/source/_static/theme_overrides.css, docs/source/bufr4_descriptors.rst, docs/source/example.rst, docs/source/installation.rst, docs/source/mapping.rst, docs/source/quickstart.rst
- adds `http://www.wmo.int/spec/om-profile-1/-/req/geojson` to GeoJSON `conformsTo` array
- replace all tabs with spaces
=> add WMO conformance

csv2bufr/__init__.py
This reverts commit 313da42d019e7b041beab1bd487d9d6bc0423571.
=> Revert "back to dev"

csv2bufr/__init__.py, csv2bufr/resources/mappings/307091_bufr.json, csv2bufr/resources/mappings/mapping_schema.json, csv2bufr/resources/mappings/synop_bufr.json, docs/source/mapping.rst, docs/source/quickstart.rst, docs/source/resources/bufr-mappings.json, tests/test_csv2bufr.py
In support of https://github.com/wmo-im/wis2box/issues/280
=> normalize on wigos_station_identifier

csv2bufr/__init__.py, docs/source/quickstart.rst, tests/test_csv2bufr.py
=> update message _meta object to be a GeoJSON (#25)

csv2bufr/__init__.py, csv2bufr/cli.py
- None returned if column not found in CSV (with warning raised).
- NULLIFY_INVALID read from environment variable.
=> - Improved messages from errors.

.github/workflows/tests.yml, Dockerfile, csv2bufr/__init__.py, csv2bufr/cli.py, requirements.txt
Addition of status to returned object from transform().
Removal of unused modules and libraries.
=> Feature addition of status

.github/workflows/dhcr.yml, Dockerfile, csv2bufr/__init__.py, csv2bufr/cli.py, csv2bufr/pygeoapi_plugin.py, csv2bufr/resources/mappings/mapping_schema.json, docs/source/example.rst, tests/test_csv2bufr.py
- more flexible WSI specification
- delimiter and quoting options in mapping template
- push to dockerhub
=> Improved templates

Dockerfile
=> Addition of editors to base image.

csv2bufr/__init__.py
csv schema should be developed and enforced to address some of these issues.
=> bug introduced by prior bug fix :-(, now fixed.

csv2bufr/__init__.py, csv2bufr/cli.py
=> Fix to catch missed exceptions. Improved error messages.

.gitignore, csv2bufr/__init__.py
=> Bugfix delayed descriptors

csv2bufr/__init__.py, csv2bufr/cli.py, csv2bufr/templates/__init__.py
Fixes https://github.com/wmo-im/csv2bufr/issues/141
=> Data mappings fix

Dockerfile, csv2bufr/__init__.py, docs/source/installation.rst
- Use latest dim eccodes base image
- Update to use latest csv2bufr templates
=> Docker update

csv2bufr/templates/__init__.py
Addition of extra try catch blocks when loading json from file.
=> Mapping schema error handling

csv2bufr/cli.py
this fixes the messy output for `csv2bufr mappings list `  :
csv2bufr mappings list
```
{"52915a45-02ab-4959-8e3b-9c8c26ddd18b": {"label": "Surface land stations (Campbell - Africa)", "description": "Mapping template for converting CSV data from Campbell data loggers configured and deployed in Africa to BUFR seqeunce 301150, 307080.", "version": "1", "author": "David I. Berry", "dateCreated": "2024-02-14", "id": "52915a45-02ab-4959-8e3b-9c8c26ddd18b", "path": "/opt/csv2bufr/templates/CampbellAfrica-v1-template.json", "name": "CampbellAfrica-v1-template"}, "2fe51aa5-d98a-4712-9954-45c7075462da": {"label": "daycli-template", "description": "Mapping template for converting daily climate CSV data to BUFR sequence 307075", "version": "3", "author": "David I. Berry", "dateCreated": …
```
=> fix csv2bufr mappings list
